name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set base in vite.config.js
        run: |
          if [[ -f "vite.config.js" ]]; then
            sed -i "s/base: '\/'/base: '\/ava'/" vite.config.js
          else
            echo "vite.config.js file not found."
            exit 1
          fi

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.AVA_SECRET }}
          publish_dir: ./dist
